project_id = "gbrbtdfrbrfrdumwjwyi"

[functions.confirm-newsletter]
verify_jwt = false

[functions.create-partner-checkout]
verify_jwt = false

[functions.stripe-partner-webhook]
verify_jwt = false

[functions.check-partner-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false